---
- name: cronjobs playbook
  hosts: vmdemo
  become: yes
  become_user: root
  tasks:
  - name: upgrade the system
    cron:
      name: upgrade every hour
      minute: "0"
      job: sudo apt upgrade -y

  - name: date
    cron:
      name: save the date every 5 minutes
      minute: "*/5"
      job: date >> /tmp/datetime.txt
